NUMBER_FOOD = 50
NUMBER_BOB = 1
FRAME_RATE = 60
TICK = 100

GRID_SIZE = 20
CELL_SIZE = 32 / 2

DEFAULT_ENERGY = 100
ENERGY_TO_REPRODUCE = 150
LOSE_ENERGY_AFTER_SEX = 100
NEW_ENERGY_SEXUAL_REPRODUCE = 100
NEW_ENERGY_PARTH_REPRODUCE = 50
MAX_ENERGY = 200

DEFAULT_PERCEPTION = 0
DEFAULT_SPEED = 2
DEFAULT_MASS = 1
DEFAULT_MEMORY = 0


# Name_file_image
BOB_IMAGE = "bob.png"
FOOD_IMAGE = "apple.png"
CELL_IMAGE = "grass.png"