NUMBER_FOOD = 100
NUMBER_BOB = 50
GRID_SIZE = 100
CELL_SIZE = 32 / 2
ENERGY_TO_REPRODUCE = 150
LOSE_ENERGY_AFTER_SEX = 100
NEW_ENERGY_REPRODUCE = 100
FRAME_RATE = 60

# Name_file_image
BOB_IMAGE = "bob.png"
FOOD_IMAGE = "apple.png"
CELL_IMAGE = "grass.png"